version: '3.1'
 
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
  web_api:
    #volumes:
    #- ./lets-get-lunch-api/:/usr/src/app ## don't net a volume mapping in non dev environment
    #- /usr/src/app/node_modules
    image: "letsgetlunchapi:B${BUILD_NUMBER}"
    ports:
    - "8080:8080"
    - 9229:9229
    command: bash -c "gulp && npm run api-test"
    depends_on:
    - mongo

  web_app:
    #volumes:
    #- ./lets-get-lunch/:/usr/src/app ## don't net a volume mapping in non dev environment
    #- /usr/src/app/node_modules
    image: "letsgetlunchapp:B${BUILD_NUMBER}"
    ports:
    - "4200:4200"
    command: bash -c "ng test --watch=false && ng serve --host 0.0.0.0"
    depends_on:
    - web_api

  cypress:
    image: "letsgetlunchcyp:B${BUILD_NUMBER}"
    command: bash -c "./node_modules/.bin/cypress run --config baseUrl=http://127.0.0.1"
    depends_on:
      - web_app
    network_mode: 'host'
    
volumes:
    data-volume:
