FROM node:10

# Create app directory
WORKDIR /usr/src/app

RUN npm install -g @angular/cli
RUN apt-get update \
    && apt-get install -y --no-install-recommends chromium

# Install app dependencies
COPY package*.json .

RUN npm install

ENV CHROME_BIN=chromium

COPY . .

#Expose port and start application
EXPOSE 4200
